name: Test and build ninnin

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Fix mpv.d.ts
        run: curl -sLo node_modules/mpv.d.ts/mpv.d.ts https://github.com/Kagami/mpv.d.ts/raw/master/mpv.d.ts
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Release nightly
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          prerelease: true
          name: nightly
          tag_name: nightly
          files: ninnin.js
          fail_on_unmatched_files: true
      - name: Release stable
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ninnin.js
          fail_on_unmatched_files: true
